---
apiVersion: v2
name: ngrok-operator
description: Ngrok operator provide developer easy access to private Kubernetes cluster for testing purpose via ngrok. Automate the creation of ngrok tunnel via CRD and automatically reload ngrok session when expired!
version: 1.1.0
appVersion: 1.2.0
type: application
home: https://github.com/zufardhiyaulhaq/ngrok-operator

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com
